INSERT INTO category (description) VALUES ('American');
INSERT INTO category (description) VALUES ('Italian');
INSERT INTO category (description) VALUES ('Mexican');
INSERT INTO category (description) VALUES ('Fast Food');
INSERT INTO unit_of_measure (description) VALUES ('Teaspoon');
INSERT INTO unit_of_measure (description) VALUES ('Tablespoon');
INSERT INTO unit_of_measure (description) VALUES ('Cup');
INSERT INTO unit_of_measure (description) VALUES ('Pinch');
INSERT INTO unit_of_measure (description) VALUES ('Ounce');
INSERT INTO unit_of_measure (description) VALUES ('Each');
INSERT INTO unit_of_measure (description) VALUES ('Dash');
INSERT INTO ingredient (description) VALUES ('avocado');
INSERT INTO ingredient (description) VALUES ('salt');
INSERT INTO ingredient (description) VALUES ('lime juice');
INSERT INTO ingredient (description) VALUES ('onion');
INSERT INTO ingredient (description) VALUES ('serrano chiles');
INSERT INTO ingredient (description) VALUES ('cilantro');
INSERT INTO ingredient (description) VALUES ('peper');
INSERT INTO ingredient (description) VALUES ('tomato');
INSERT INTO ingredient (description) VALUES ('jicama');
INSERT INTO ingredient (description) VALUES ('chips');